<a href="https://colab.research.google.com/github/DeepthiTabithaBennet/NaturalLanguageProcessing/blob/main/NLP_Syntactic_Analysis_POS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **Plain**

In [ ]:
import nltk

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

In [ ]:
def pos_tagging(text):

    tokens = nltk.word_tokenize(text)
    pos_tags = nltk.pos_tag(tokens)

    return pos_tags

In [ ]:
sample_text = "The quick brown fox jumps over the lazy dog."
tagged_output = pos_tagging(sample_text)

for word, tag in tagged_output:
    print(word, ":", tag)

The : DT
quick : JJ
brown : NN
fox : NN
jumps : VBZ
over : IN
the : DT
lazy : JJ
dog : NN
. : .


## **HMM & Viterbi**

In [ ]:
import nltk
from nltk.tag import hmm

nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [ ]:
data = "Mary Jane can see will. The spot will see Mary. Will Jane spot Mary? Mary will pat Spot"

sentences = nltk.sent_tokenize(data)
training_data=[]

for sentence in sentences:
    words = nltk.word_tokenize(sentence)
    pos_tags = nltk.pos_tag(words)
    training_data.append(pos_tags)


hmm_tagger = hmm.HiddenMarkovModelTrainer().train(training_data)
sentence = ["The","dog","runs", "fast"]
pos_tags = hmm_tagger.tag(sentence)
print("Tagged sentence : ", pos_tags)

Tagged sentence :  [('The', 'NNP'), ('dog', 'NNP'), ('runs', 'NNP'), ('fast', 'NNP')]


/usr/local/lib/python3.10/dist-packages/nltk/tag/hmm.py:334: RuntimeWarning: overflow encountered in cast
  X[i, j] = self._transitions[si].logprob(self._states[j])
/usr/local/lib/python3.10/dist-packages/nltk/tag/hmm.py:336: RuntimeWarning: overflow encountered in cast
  O[i, k] = self._output_logprob(si, self._symbols[k])
/usr/local/lib/python3.10/dist-packages/nltk/tag/hmm.py:332: RuntimeWarning: overflow encountered in cast
  P[i] = self._priors.logprob(si)
/usr/local/lib/python3.10/dist-packages/nltk/tag/hmm.py:364: RuntimeWarning: overflow encountered in cast
  O[i, k] = self._output_logprob(si, self._symbols[k])


In [ ]:
data = "Mary Jane can see will. The spot will see Mary. Will Jane spot Mary? Mary will pat Spot"

sentences = nltk.sent_tokenize(data)
training_data=[]

for sentence in sentences:
    words = nltk.word_tokenize(sentence)
    pos_tags = nltk.pos_tag(words)
    training_data.append(pos_tags)

hmm_tagger = nltk.HiddenMarkovModelTagger.train(training_data)

sentence1 = ["The","dog","runs", "fast"]
pos_tags = hmm_tagger.tag(sentence1)
print("Tagged sentence : ", pos_tags)

Tagged sentence :  [('The', 'DT'), ('dog', 'NN'), ('runs', 'MD'), ('fast', 'VB')]


In [ ]:
! pip install hmmlearn

In [ ]:
import numpy as np
from hmmlearn import hmm

# Sample training data: sequences of observed words and their corresponding POS tags
observations = ['the', 'dog', 'barks', 'loudly', 'the', 'cat', 'meows']
pos_tags = ['DET', 'NOUN', 'VERB', 'ADV', 'DET', 'NOUN', 'VERB']

# Map words and tags to indices
word_to_index = {word: i for i, word in enumerate(set(observations))}
tag_to_index = {tag: i for i, tag in enumerate(set(pos_tags))}

# Convert observations and tags to indices
X = np.array([[word_to_index[word]] for word in observations])
lengths = [len(observations)]

# Create and train the HMM
model = hmm.MultinomialHMM(n_components=len(tag_to_index), n_iter=100)
model.fit(X, lengths)

# Now, let's test the HMM with a new sequence
test_sequence = ['the', 'cat', 'barks']
X_test = np.array([[word_to_index[word]] for word in test_sequence])

# Use the Viterbi algorithm to find the best tag sequence
logprob, tag_sequence = model.decode(X_test, algorithm='viterbi')

# Convert indices back to tags
predicted_tags = [list(tag_to_index.keys())[tag] for tag in tag_sequence]

# Print results
print("Test Sequence:", test_sequence)
print("Predicted Tags:", predicted_tags)

https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


Test Sequence: ['the', 'cat', 'barks']
Predicted Tags: ['DET', 'DET', 'DET']


In [ ]:
import numpy as np
from hmmlearn import hmm

# Sample training data: sequences of observed words and their corresponding POS tags
observations = ['the', 'dog', 'barks', 'loudly', 'the', 'cat', 'meows']
pos_tags = ['DET', 'NOUN', 'VERB', 'ADV', 'DET', 'NOUN', 'VERB']

# Create mappings from words and tags to indices
# This allows us to convert our words and tags into numerical format
word_to_index = {word: i for i, word in enumerate(set(observations))}
tag_to_index = {tag: i for i, tag in enumerate(set(pos_tags))}

# Convert observations to indices
# The HMM expects numerical input, so we transform our words into their corresponding indices
X = np.array([[word_to_index[word]] for word in observations])

# Initialize and train the HMM
# We specify the number of components (states) based on unique POS tags
model = hmm.MultinomialHMM(n_components=len(tag_to_index), n_iter=100)
model.fit(X)

# Test sequence of words for prediction
test_sequence = ['the', 'cat', 'barks']
# Convert the test sequence to indices using the same mapping
X_test = np.array([[word_to_index[word]] for word in test_sequence])

# Use the Viterbi algorithm to predict the most likely sequence of tags
logprob, tag_sequence = model.decode(X_test, algorithm='viterbi')

# Convert predicted tag indices back to their corresponding string representations
# This uses the tag_to_index mapping to get the original tags
predicted_tags = []
for tag_index in tag_sequence:
    # Find the tag corresponding to the index
    predicted_tags.append(list(tag_to_index.keys())[tag_index])

# Output the results
print("Test Sequence:", test_sequence)
print("Predicted Tags:", predicted_tags)


https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


Test Sequence: ['the', 'cat', 'barks']
Predicted Tags: ['DET', 'NOUN', 'VERB']


In [ ]:
import numpy as np
from hmmlearn import hmm

# Sample training data: sequences of observed words and their corresponding POS tags
observations = ['the', 'dog', 'barks', 'loudly', 'the', 'cat', 'meows']
pos_tags = ['DET', 'NOUN', 'VERB', 'ADV', 'DET', 'NOUN', 'VERB']

# Create mappings from words and tags to indices
word_to_index = {word: i for i, word in enumerate(set(observations))}
tag_to_index = {tag: i for i, tag in enumerate(set(pos_tags))}

# Convert observations to indices
X = np.array([[word_to_index[word]] for word in observations])

# Initialize and train the HMM
model = hmm.MultinomialHMM(n_components=len(tag_to_index), n_iter=100)
model.fit(X)

# Display transition and emission probabilities
print("Transition Matrix:")
print(model.transmat_)  # Transition probabilities

print("\nEmission Matrix:")
print(model.emissionprob_)  # Emission probabilities

# Test sequence of words for prediction
test_sequence = ['the', 'cat', 'barks']
X_test = np.array([[word_to_index[word]] for word in test_sequence])

# Use the Viterbi algorithm to predict the most likely sequence of tags
logprob, tag_sequence = model.decode(X_test, algorithm='viterbi')

# Convert predicted tag indices back to their corresponding string representations
predicted_tags = [list(tag_to_index.keys())[tag] for tag in tag_sequence]

# Output the results
print("\nTest Sequence:", test_sequence)
print("Predicted Tags:", predicted_tags)


https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340


Transition Matrix:
[[1.56032888e-01 1.12469583e-01 6.66403358e-01 6.50941714e-02]
 [6.83507168e-02 2.76691546e-01 3.43107588e-01 3.11850149e-01]
 [7.91015892e-01 2.08342867e-01 6.41001227e-04 2.40274929e-07]
 [6.63055887e-03 3.60203316e-01 5.95982602e-01 3.71835230e-02]]

Emission Matrix:
[[1.]
 [1.]
 [1.]
 [1.]]

Test Sequence: ['the', 'cat', 'barks']
Predicted Tags: ['DET', 'VERB', 'NOUN']


In [ ]:
# https://pypi.org/project/FastHMM/

! pip install FastHMM

In [ ]:
from FastHMM.hmm import HMMModel
from FastHMM.non_rec_viterbi import Viterbi


# test model training and predict
hmm_model = HMMModel()
hmm_model.train_one_line([("I", "r"), ("love", "v"), ("Beijing", "ns"), ("Tiananmen", "ns")])
hmm_model.train_one_line([("you", "r"), ("go", "v"), ("Shenzhen", "ns")])
result = hmm_model.predict(["me", "love", "Guangzhou"])
print(result)

# test save and load model
hmm_model.save_model()
hmm_model = HMMModel().load_model()
result = hmm_model.predict(["we", "love", "Shenzhen"])
print(result)


STATE = ['A', 'B', 'C']

PI = {'A': .8}

A = {'A': {'A': 0.1,
           'B': .7,
           'C': .2, },
     'B': {'A': .1,
           'B': 0.1,
           'C': .8},
     'C': {'A': .1,
           'B': 0.1,
           'C': .8}}

B = {'A': {'you': 0.5,
           'I': 0.5},
     'B': {'are': 0.4,
           'speak': 0.6},
     'C': {'person': 0.5,
           'Chinese': 0.5}}

viterbi_model = Viterbi(A, B, PI, STATE)
trace = viterbi_model.predict_state(["I", "speak", "Chinese"])
print(trace)
state_sequence = viterbi_model.predict_state(["I", "are", "Chinese"])
print(state_sequence)

[('me', 'r'), ('love', 'v'), ('Guangzhou', 'ns')]
[('we', 'r'), ('love', 'v'), ('Shenzhen', 'ns')]
(['A', 'B', 'C'], 3.9000000000000004)
(['A', 'B', 'C'], 3.7)


In [ ]:
! pip install hmmlearn

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from hmmlearn import hmm

# state space
states_space = ["Sunny", "Rainy", "Winter"]
no_of_states = len(states_space)
print('Number of hidden states :',no_of_states)
# observation space
observations_space = ["Dry", "Wet", "Humid"]
no_of_observations = len(observations_space)
print('Number of observations  :',no_of_observations)

# state distribution
state_probab = np.array([0.5, 0.4, 0.1])
print("The State probability: ", state_probab)

# transition probabilities
transition_probab = np.array([[0.2, 0.3, 0.5],
                                   [0.3, 0.4, 0.3],
                                   [0.5, 0.3, 0.2]])
print("\nThe Transition probability:\n", transition_probab)
# emission probability
emission_probab = np.array([[0.2, 0.1, 0.7],
                                 [0.2, 0.5, 0.3],
                                 [0.4, 0.2, 0.4]])
print("\nThe Emission probability:\n", emission_probab)

model = hmm.CategoricalHMM(n_components=no_of_states)
model.startprob_ = state_probab
model.transmat_ = transition_probab
model.emissionprob_ = emission_probab

observations_sequence = np.array([0, 1, 0, 1, 0, 0]).reshape(-1, 1)
observations_sequence

hidden_states = model.predict(observations_sequence)
print("The Most likely hidden states are:", hidden_states)

log_probab, hidden_states = model.decode(observations_sequence,
                                              lengths = len(observations_sequence),
                                              algorithm ='viterbi' )

print('Log Probability :',log_probab)
print("Most likely hidden states:", hidden_states)

Number of hidden states : 3
Number of observations  : 3
The State probability:  [0.5 0.4 0.1]

The Transition probability:
 [[0.2 0.3 0.5]
 [0.3 0.4 0.3]
 [0.5 0.3 0.2]]

The Emission probability:
 [[0.2 0.1 0.7]
 [0.2 0.5 0.3]
 [0.4 0.2 0.4]]
The Most likely hidden states are: [1 1 2 1 2 0]
Log Probability : -12.575398707022462
Most likely hidden states: [1 1 2 1 2 0]
